from dataclasses import dataclass


@dataclass(frozen=True)
class RedditAuth:
    client_id: str = "JdYlCavPJLyMBfA5_vtrbw"
    client_secret: str = "Dl3cfMYcZ29kA4xhx8NVsE7jNZFqkA"
    user_agent: str = "NGO_Issue_Analyzer/1.0"


ISSUE_CONFIGS = {
    "Food Insecurity": {
        "subreddits": [
            "foodsecurity",
            "hunger",
            "poverty",
            "assistance",
            "foodinsecurity",
            "homeless",
            "charity",
            "donate",
            "food",
            "nutrition",
            "mealprep",
            "budgetfood",
            "cheapeats",
        ],
        "keywords": [
            "food insecurity",
            "hunger",
            "food bank",
            "food pantry",
            "starvation",
            "malnutrition",
            "food assistance",
            "free food",
            "emergency food",
            "meal assistance",
            "food crisis",
            "food shortage",
            "food",
            "meal",
            "eat",
            "help",
            "support",
            "need",
            "free",
            "donation",
            "poverty",
            "homeless",
            "struggling",
            "resources",
        ],
    },
    "Housing/Homelessness": {
        "subreddits": [
            "homeless",
            "housing",
            "rent",
            "landlord",
            "tenant",
            "eviction",
            "affordablehousing",
            "homelessness",
            "shelter",
            "street",
            "couchsurfing",
            "houseless",
            "housingcrisis",
            "homelessnessinamerica",
            "homelessshelter",
        ],
        "keywords": [
            "homeless",
            "homelessness",
            "housing crisis",
            "affordable housing",
            "eviction",
            "rent",
            "shelter",
            "street",
            "housing insecurity",
            "housing assistance",
            "homeless shelter",
            "tent city",
            "housing",
            "home",
            "apartment",
            "landlord",
            "tenant",
        ],
    },
    "Employment/Unemployment": {
        "subreddits": [
            "unemployment",
            "jobs",
            "career",
            "recruiting",
            "jobsearch",
            "work",
            "employment",
            "hiring",
            "resume",
            "interview",
            "jobless",
            "laidoff",
            "fired",
            "careerguidance",
            "worklife",
        ],
        "keywords": [
            "unemployment",
            "job loss",
            "laid off",
            "fired",
            "job search",
            "employment",
            "career",
            "hiring",
            "workplace",
            "job market",
            "unemployed",
            "job security",
            "employment assistance",
            "work",
            "job",
            "interview",
        ],
    },
    "Gender Inequality": {
        "subreddits": [
            "feminism",
            "womensrights",
            "equality",
            "genderequality",
            "sexism",
            "womenshealth",
            "womensupportingwomen",
            "girlsgonewired",
            "ladybusiness",
            "women",
            "gender",
            "paygap",
            "metoo",
            "womenintech",
            "feminists",
        ],
        "keywords": [
            "gender inequality",
            "pay gap",
            "sexism",
            "discrimination",
            "gender bias",
            "women's rights",
            "feminism",
            "gender equality",
            "sexual harassment",
            "gender discrimination",
            "glass ceiling",
            "women",
            "gender",
            "equality",
            "rights",
            "discrimination",
        ],
    },
}





